### ISSUE TITLE
GLRepo Data Never Set

### ISSUE THREAD

**Issue by justinorringer** [RedHatInsights/platform-changelog-go#6]
services.yml:

```
insights-engine:
    display_name: Insights Engine
    gl_repo: https://gitlab.cee.redhat.com/insights-platform/insights-engine
    branch: main
    namespace: engine-prod
```

DB: 
![Screenshot from 2022-06-22 10-52-55](https://user-images.githubusercontent.com/87503474/175060728-81965dab-77e2-4a17-b126-bbf3b2845658.png)
